<?php echo $this->doctype(); ?>

<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <base href="<?php echo $this->escape($this->ServerUrl() . $this->baseUrl()); ?>" />
<?php
    echo $this->headMeta()->setIndent(4) . PHP_EOL;
    echo $this->headTitle()->setIndent(4) . PHP_EOL;
    echo $this->headLink()->setIndent(4)
                     ->appendStylesheet('modules/admin/css/screen.css', 'screen, projection')
                     ->appendStylesheet('modules/admin/css/ie.css', 'screen, projection', 'lt IE 7');
                    // ->appendStylesheet('css/blueprint/screen.css', 'screen, projection')
                    // ->appendStylesheet('css/blueprint/print.css', 'print')
                    // ->appendStylesheet('css/blueprint/ie.css', 'screen, projection', 'lt IE 8')
                    // ->appendStylesheet('css/main.css', 'screen, projection');
    echo $this->headStyle()->setIndent(4) . PHP_EOL;
    $this->addHelperPath("ZendX/JQuery/View/Helper", "ZendX_JQuery_View_Helper");
    echo $this->JQuery()
            ->addStylesheet('css/jquery/smoothness/jquery-ui-1.7.3.custom.css');
?>
</head>
<body>

    <div class="page_margins">
        <div class="page">

            <div id="header">
                <div id="topnav">
                    <a>Home</a> | <a>Logout</a>

                </div>
            </div>

<!--            <div id="nav">
                 skiplink anchor: navigation 
                <div class="hlist">
                     main navigation: horizontal list 
                    <ul>
                        <li class="active"><strong>Button 1</strong></li>
                        <li><a href="#">Button 2</a></li>
                        <li><a href="#">Button 3</a></li>
                        <li><a href="#">Button 4</a></li>
                        <li><a href="#">Button 5</a></li>
                    </ul>
                </div>
            </div>-->

            <div id="teaser">
                <?php echo $this->navigationWidget('admin')->breadcrumbs()->setMinDepth(1)->setLinkLast(true)->setSeparator(' > '); ?>

            </div>
            <!-- end teaser -->

            <div id="main">
                <div id="col1">
                    <div id="col1_content" class="clearfix">

                        <!-- add your content here -->
                        <div class="messages">

                            <?php if (!empty($this->messages)) : ?>
                            <?php foreach ($this->messages as $message) : ?>
                                    <p><?php echo $this->escape($message); ?></p>
                            <?php endforeach; ?>
                            <?php endif; ?>

                        </div>

                        <h1>This is admin Layout</h1>

                        <?php echo $this->layout()->content; ?>

                    </div>
                </div>

                <div id="col3">
                    <div id="col3_content" class="clearfix">

                        <?php echo $this->navigationWidget('admin')->menu()->setMaxDepth(1)->setIndent(12); ?>

                    </div>
                    <!-- IE Column Clearing -->
                    <div id="ie_clearing">   </div>
                </div>
            </div>
            <!-- end main -->


            <!-- begin: #footer -->
            <div id="footer">
                Layout based on <a href="http://www.yaml.de/">YAML</a>
            </div>

        </div>
    </div>
<?php
    // read this http://developer.yahoo.com/performance/rules.html#js_bottom
    // or russian http://webo.in/articles/habrahabr/15-yahoo-best-practices/#javascript
    echo $this->headScript()->setIndent(4);
?>
</body>
</html>