<?php
namespace App\Admin\Model\Domain\Validator;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for AddMenuValidator.
 * Generated by PHPUnit on 2010-10-11 at 18:40:24.
 */
class AddMenuValidatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AddMenuValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AddMenuValidator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
