        <div id="welcome">
            <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>

            <h3>This is your project's main page</h3>

            <div id="more-information">
                <p><!--img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /--></p>
                <p>
                    Helpful Links: <br />
                    <a href="http://framework.zend.com/">Zend Framework Website</a> |
                    <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
                </p>
            </div>

        </div>
