<?php echo $this->doctype() . "\n"; ?>
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <base href="<?php echo $this->escape($this->baseUrl()); ?>" />
<?php 
    echo $this->headMeta()->setIndent('    ') . "\n";
    echo $this->headTitle()->setIndent('    ') . "\n";
    echo $this->headLink()->setIndent('    ')
                     ->appendStylesheet('css/blueprint/screen.css', 'screen, projection')
                     ->appendStylesheet('css/blueprint/print.css', 'print')
                     ->appendStylesheet('css/blueprint/ie.css', 'screen, projection', 'lt IE 8')
                     ->appendStylesheet('css/main.css', 'screen, projection');
    echo $this->headStyle()->setIndent('    ');
?>

</head>
<body>

    <div class="container showgrid">

        <h1>This is Layout</h1>
<?php echo $this->layout()->content; ?>

    </div>

<?php 
// read plz http://webo.in/articles/habrahabr/15-yahoo-best-practices/#javascript
echo $this->headScript()->setIndent('    '); ?>
    
</body>
</html>