<?php

/**
 *  CMF for web applications based on Zend Framework 1 and Doctrine 2
 *  Copyright (C) 2010  Eugene Gruzdev aka yugeon
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @copyright  Copyright (c) 2010 yugeon <yugeon.ru@gmail.com>
 * @license    http://www.gnu.org/licenses/gpl-3.0.html  GNU GPLv3
 */
?>

<?php

    $outputHtml = '';

    if (is_array($this->messages))
    {
        foreach ($this->messages as $message)
        {
            $outputHtml .= '<p>' . $this->escape($message) . '</p>';
        }
    }

    if (!empty($this->form))
    {
        // hide control elements becouse they present in the dialog box
        $this->form->getElement('submit')
                   ->setDecorators(array('ViewHelper'))
                   ->setAttrib('style', 'display:none;');
        $this->form->getElement('reset')
                   ->setDecorators(array('ViewHelper'))
                   ->setAttrib('style', 'display:none;');
        $outputHtml .= (string) $this->form;
    }
?>

<?php 
    ZendX_JQuery::enableView($this);
    $this->JQuery()->onLoadCaptureStart();
?>

    $('#<?php echo $this->escape($this->form->getName()); ?>').submit(function(){
        var thisForm = this;
        $.ajax({
            url: '/admin/navigation/add-page/format/json',
            dataType: 'json',
            type: 'post',
            data: $(this).serialize().concat('&submit=1'),
            beforeSend: function(){
                $(thisForm).parent().ajaxLoader();
            },
            timeout: 10000,
            error: function(){
                this.showError('An error occurred while add new page. Try again later.');
            },
            success: function(data){
                if (!data || data.error) {
                    this.showError(data.error.message);
                    return;
                } else {
                    var html = data.result.html;
                    $(thisForm).parent().html(html).ajaxLoader('showClass', 'ajax-loader-ok', 1);
                }
            },
            showError: function(msg){
                $('#add-page-form').ajaxLoader('showClass', 'ajax-loader-error');
                if (msg) {
                    alert(msg);
                }
            }
        });
        
        return false;
    });

<?php
    $this->JQuery()->onLoadCaptureEnd();
    $outputHtml .= (string) $this->JQuery()->setRenderMode(ZendX_JQuery::RENDER_JQUERY_ON_LOAD);
?>

{
    "result":
    {
        "html": <?php echo $this->json($outputHtml); ?>
    }
}
