
<?php foreach ($this->menuList as $menu): ?>
    <?php $id = $this->escape($menu->getId()); ?>
        <p>
            <?php echo $this->escape($menu->getName()); ?>
            | <a href='<?php echo $this->url(array('action' => 'edit-menu', 'name' => $this->escape($menu->getName()))); ?>'>Edit</a>
            | <a href='<?php echo $this->url(array('action' => 'delete', 'name' => $this->escape($menu->getName()))); ?>'>Delete</a>
        </p>
<?php endforeach;?>