
<?php foreach ($this->menuList as $menu): ?>
    <?php $id = $this->escape($menu->getId()); ?>
        <p>
            <?php echo $this->escape($menu->getName()); ?>
            | <a href='<?php echo $this->url(array('action' => 'edit', 'id' => $id)); ?>'>Edit</a>
            | <a href='<?php echo $this->url(array('action' => 'delete', 'id' => $id)); ?>'>Delete</a>
        </p>
<?php endforeach;?>